### ISSUE TITLE
More fine-grained matching of Baining languages

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/languageatlasofthepacificarea#10]
For the languages of Northern New Britain, only Asimbali and Uramot (with typo Jramot) are given with their dialect names in the shape metadata. Kakat and Gaktai are only given as BAINING

![Screenshot from 2024-11-26 15-40-42](https://github.com/user-attachments/assets/2cf6b693-b6a7-4a0f-9f5e-059253fc11ae)

Based on alternative names and location, it seems likely that Kakat is [Qaqet](https://glottolog.org/resource/languoid/id/qaqe1238) and Gaktai is [Mali](https://glottolog.org/resource/languoid/id/mali1284) (although the latter only has Gaktai as alternative name from multitree - which may be because someone back then had to also map Gaktai to anything with an ISO code when looking at Wurm & Hattiri's map ... but then, the ISO code starts with a "g" :) ).

**Comment by xrotwang** [comment]
@d97hah  thoughts?

**Comment by xrotwang** [comment]
Ah. other web sources seem to suggest that Gaktai is the name of the people while Mali is the name of their language.

**Comment by d97hah** [comment]
Agree,  Kakat is Qaqet
<https://glottolog.org/resource/languoid/id/qaqe1238> and
Gaktai is Mali <https://glottolog.org/resource/languoid/id/mali1284>.

Pada Sel, 26 Nov 2024 pukul 15.51 Robert Forkel ***@***.***>
menulis:
