### ISSUE TITLE
More fine-grained mapping for areas matched to Bali-Vitu

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/languageatlasofthepacificarea#11]
Below is the W&H map for [Bali-Vitu](https://glottolog.org/resource/languoid/id/bali1280). Glottolog lists two languages in this group - Uneapa and Muduapa. It would seem reasonable to match the polygon on Unea to Uneapa and the other two to Muduapa - even though W&H only give Bali-Vitu as label.

![Screenshot from 2024-11-28 09-13-33](https://github.com/user-attachments/assets/fbfd44f5-65d2-4b4f-a148-f70891dc8b8e)

**Comment by xrotwang** [comment]
@d97hah agree?

**Comment by d97hah** [comment]
Agree!

Pada Kam, 28 Nov 2024 pukul 09.18 Robert Forkel ***@***.***>
menulis:
