### ISSUE TITLE
Find a way to transparently fix polygons that are slightly off

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/languageatlasofthepacificarea#3]
![Screenshot from 2024-04-26 17-45-21](https://github.com/cldf-datasets/languageatlasofthepacificarea/assets/870184/8758e8d3-822a-4638-aef6-515363ef76fd)

**Comment by xrotwang** [comment]
Some way of specifying translations. E.g.

```
Latitude	 -13.7555
Longitude  -172.9456
->
Latitude	-13.4847
Longitude	-172.7806
```

**Comment by SimonGreenhill** [comment]
+offset_x;+offset_y? 

Looks like a projection error -- is there a way to check the original projection?

**Comment by xrotwang** [comment]
> Looks like a projection error -- is there a way to check the original projection?

That's what I thought first. But the errors are not really consistent. They are sort of consistent within island group - so maybe multiple maps have pasted together at some point. I think fixing the issues "manually", and as they are encountered is more pragmatic and efficient than trying to re-engineer the actual cause.

**Comment by xrotwang** [comment]
Sometimes not even consistent within island group ... :)

![Screenshot from 2024-04-29 10-53-44](https://github.com/cldf-datasets/languageatlasofthepacificarea/assets/870184/02521946-f7db-4dc7-ab56-b9899cf02ede)

**Comment by SimonGreenhill** [comment]
oh dear :/  that does look like some maps hae been pasted together - the top left islands look like approximation with a polygon, while the bottom right looks smoother.

**Comment by xrotwang** [comment]
see https://github.com/cldf-datasets/languageatlasofthepacificarea/blob/main/lib/move_polygons.py

**Comment by SimonGreenhill** [comment]
cool! nice work
