### ISSUE TITLE
ASARO incorrectly mapped to asar1240

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/languageatlasofthepacificarea#6]
ASARO is probably one of the languages in the [Gahuku family](https://glottolog.org/resource/languoid/id/gahu1246). Dano and Tokano have dialects Upper/Lower Asaro.
https://github.com/cldf-datasets/languageatlasofthepacificarea/blob/8883352b08516e26261a8e060a40db40f34619fa/etc/languages.csv#L1943

**Comment by xrotwang** [comment]
Note that the ASARO polygon is lumped together with the one for MORAFA with a multi-polygon spread of ~1.2 (see
https://github.com/cldf-datasets/languageatlasofthepacificarea/blob/8883352b08516e26261a8e060a40db40f34619fa/etc/multipolygon_spread.csv#L19 ), below our cut-off for unusually big spread of 2.

**Comment by d97hah** [comment]
asar1240 is indeed wrong. Asaro in Scott 1978, probably the underlying source, is Dano [aso]. Maybe it requires further checking, but the ID of this Asaro and Dano [aso] should be as good as the language/division status itself.

**Comment by xrotwang** [comment]
It's good to see that we have a tool to detect such cases (multiple areas erroneously mapped to the same language), just need to fine-tune the thresholds.
