### ISSUE TITLE
map MIKAREW to Aruamu

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/languageatlasofthepacificarea#7]
Currently, the area labeled MIKAREW in the atlas is mapped to the subgroup Mikarewan. But one of the two languages in this subgroup corresponds to the neighboring area labeled SEPEN. The other Mikarewan language - [Aruamu](https://glottolog.org/resource/languoid/id/arua1260) - has alternative names Ariawia and Gumasi - which are used to label the same area in Asher & Moseley 2007. Thus, it seems appropriate to map MIKAREW to Aruamu.

**Comment by d97hah** [comment]
Agree
