### ISSUE TITLE
map OMATI to Barikewa

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/languageatlasofthepacificarea#8]
[Omati](https://glottolog.org/resource/languoid/id/omat1240) has been retired and is to be split into Barikewa and Mouwase. According to the map in [The Sociolinguistic Situation in the Kaser Area](https://pnglanguages.sil.org/resources/archives/61932), the area in Wurm & Hattori labeled OMATI matches rather the Barikewa-speaking area than the Mouwase-speaking area which lies between the Turama river and Omati village.

**Comment by d97hah** [comment]
Agree
