### ISSUE TITLE
map TANI to Miani

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/languageatlasofthepacificarea#9]
TANI is currently mapped to Maiani, but might be better mapped to [Miani](https://glottolog.org/resource/languoid/id/mian1254), considering that Asher & Moseley label the same area "TANI (MIAMI)".

**Comment by d97hah** [comment]
Agree. Tani can be a name for either but in Z'graggen 1975, probably the underlying source, Tani is Miani [pla].
